cloud:
  aws:
    region:
      static: us-east-2
      auto: false
    credentials:
      access-key: ****
      secret-key: ****
    end-point:
      uri: https://sqs.us-east-2.amazonaws.com/219694035291/ReadingIsGood-sqs.fifo
